version: '3.2'

services:
  elasticsearch: # Log-Storage
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: "7.16.2"
    volumes:
      - type: bind
        source: C:\Installed Software\volumes\elasticsearch\config\elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: C:\Installed Software\volumes\elasticsearch\data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
  
  logstash: # Data-Processing
    build:
      context: logstash/
      args:
        ELK_VERSION: "7.16.2"
    volumes:
      - type: bind
        source: C:\Installed Software\volumes\logstash\config\logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: C:\Installed Software\volumes\logstash\pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  kibana: # Visualizer
      build:
        context: kibana/
        args:
          ELK_VERSION: "7.16.2"
      volumes:
        - type: bind
          source: C:\Installed Software\volumes\kibana\config\kibana.yml
          target: /usr/share/kibana/config/kibana.yml
          read_only: true
      ports:
        - "5601:5601"
      networks:
        - elk
      depends_on: # Express dependency between services
        - elasticsearch
networks:
  elk:


