version: '3.2'

services:
  elasticsearch: # Log-Storage
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: "7.16.2"
    container_name: elasticsearch
    volumes:
      - type: bind
        source: C:\Installed Software\volumes\elasticsearch\config\elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: C:\Installed Software\volumes\elasticsearch\data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: "single-node"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
  
  logstash: # Data-Processing
    build:
      context: logstash/
      args:
        ELK_VERSION: "7.16.2"
    container_name: logstash    
    volumes:
      # Configuration files in "config" directory, including logstash.yml and jvm.options
      - type: bind
        source: C:\Installed Software\volumes\logstash\config\logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      # Logstash pipeline configuration files
      - type: bind
        source: C:\Installed Software\volumes\logstash\pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: C:\Installed Software\volumes\logstash\jars\activemq-all-5.16.3.jar
        target: /opt/activemq-all-5.16.3.jar
        read_only: false
    ports:
      - "5000:5000" #"5000:5000/tcp" or "5000:5000/udp"
      - "9600:9600" 
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  kibana: # Visualizer
      build:
        context: kibana/
        args:
          ELK_VERSION: "7.16.2"
      container_name: kibana
      volumes:
        - type: bind
          source: C:\Installed Software\volumes\kibana\config\kibana.yml
          target: /usr/share/kibana/config/kibana.yml
          read_only: true
      ports:
        - "5601:5601"
      networks:
        - elk
      depends_on: # Express dependency between services
        - elasticsearch
  
  activemq:
    build:
      context: activemq/
    container_name: activemq
    volumes:
    #  - type: bind # Not working
    #    source: C:\Installed Software\volumes\activemq\config
    #    target: /opt/activemq/conf
    #    read_only: false
      - type: bind
        source: C:\Installed Software\volumes\activemq\data
        target: /data/activemq
        read_only: false
      - type: bind
        source: C:\Installed Software\volumes\activemq\log
        target: /var/log/activemq
        read_only: false
    ports:
        # mqtt
        - "1883:1883"
        # amqp
        - "5672:5672"
        # ui
        - "8161:8161"
        # stomp
        - "61613:61613"
        # ws
        - "61614:61614"
        # jms
        - "61616:61616"
    environment:
      #ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      #ACTIVEMQ_ADMIN_LOGIN: admin
      #ACTIVEMQ_ADMIN_PASSWORD: password
      #ACTIVEMQ_WRITE_LOGIN: write
      #ACTIVEMQ_WRITE_PASSWORD: password
      #ACTIVEMQ_READ_LOGIN: read
      #ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
    networks:
        - elk
networks:
  elk:


